// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cuteAudioNet.Postgresql;

#nullable disable

namespace cuteAudioNet.Postgresql.Migrations
{
    [DbContext(typeof(PgContext))]
    [Migration("20260727084653_FixTracks_SubArtists")]
    partial class FixTracks_SubArtists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cuteAudioNet.Postgresql.Models.ModelAlbumDB", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ArtistID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateRelease")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("cuteAudioNet.Postgresql.Models.ModelArtistDB", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BornDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pathonymic")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("cuteAudioNet.Postgresql.Models.ModelTrackDB", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumID")
                        .HasColumnType("uuid");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubArtist")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeRelease")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("cuteAudioNet.Postgresql.Models.ModelAlbumDB", b =>
                {
                    b.HasOne("cuteAudioNet.Postgresql.Models.ModelArtistDB", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("cuteAudioNet.Postgresql.Models.ModelTrackDB", b =>
                {
                    b.HasOne("cuteAudioNet.Postgresql.Models.ModelAlbumDB", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("cuteAudioNet.Postgresql.Models.ModelAlbumDB", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("cuteAudioNet.Postgresql.Models.ModelArtistDB", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
